# -*- coding: utf-8 -*-
"""Question 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1us0ZWmf4976R_Mr4ZaXCC-P-h-hFR65-

**1. Binary Mask and Filter Application (Low-pass and High-pass filters)**
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load image
image = cv2.imread('/content/image.jpg', 0)  # Load as grayscale

# Create a binary mask using thresholding
_, mask = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)

# Apply Gaussian Blur (low-pass filter)
gaussian_blur = cv2.GaussianBlur(image, (5, 5), 0)

# Apply Average filter (low-pass filter)
average_blur = cv2.blur(image, (5, 5))

# Apply Laplacian filter (high-pass filter)
laplacian = cv2.Laplacian(image, cv2.CV_64F)

# Apply Prewitt filter (high-pass filter using custom kernel)
prewitt_x = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
prewitt_y = np.array([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])

prewitt_x_image = cv2.filter2D(image, -1, prewitt_x)
prewitt_y_image = cv2.filter2D(image, -1, prewitt_y)

# Show results
images = [image, mask, gaussian_blur, average_blur, laplacian, prewitt_x_image, prewitt_y_image]
titles = ['Original', 'Mask', 'Gaussian Blur', 'Average Blur', 'Laplacian', 'Prewitt X', 'Prewitt Y']

for i in range(7):
    plt.subplot(2, 4, i+1), plt.imshow(images[i], 'gray')
    plt.title(titles[i])
    plt.xticks([]), plt.yticks([])

plt.show()

